package:
  name: http
  version: v0.1.0
  authors: 
    - author: 
      email: 
      organization: chaos-io
  license: 
  dependencies: 
    - repository: github.com/chaos-io/gokit
      version: latest
  repository: github.com/chaos-io/http
